JobOffers/Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JobOffers.Models
{
    public class Job
    {
        public int JobId { get; set; }
        [Required]
        public string JobTitle { get; set; }
        [Required]
        public string JobContent { get; set; }



        public virtual Category Category { get; set; }
        public int CategoryId { get; set; }


        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

JobOffers/Controllers/JobController.cs
using JobOffers.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobOffers.ViewModel;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
namespace JobOffers.Controllers
{
    [Authorize(Roles="Publisher")]
    public class JobController : Controller
    {
        private ApplicationDbContext db;

        public JobController()
        {
            db = new ApplicationDbContext();
        }
        // GET: Job
        public ActionResult Index()
        {
         var jobs =  db.jobs
                .Include(x => x.Category)
                .ToList();
            return View(jobs);
        }

        public ActionResult New(JobViewModel job)
        {
            var jobVm = new JobViewModel
            {
                job = new Job(),
                Categories = db.categories.ToList()
            };
            return View(jobVm);
        }

        public ActionResult Save(Job job)
        {
            if (job.JobId == 0)
            {
                job.UserId = User.Identity.GetUserId();
                db.jobs.Add(job);
            }
            else
            {
                var jobInDb = db.jobs.SingleOrDefault(j => j.JobId == job.JobId);
                jobInDb.JobTitle = job.JobTitle;
                jobInDb.JobContent = job.JobContent;
                jobInDb.CategoryId = job.CategoryId;
                jobInDb.UserId = User.Identity.GetUserId();
               
            }

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var job = db.jobs.Find(id);

            var viewModel = new JobViewModel
            {
                job = job,
                Categories = db.categories.ToList()
            };

            if(job == null){
                return HttpNotFound();
            }
            return View("New", viewModel);
        }
        public ActionResult Details(int id)
        {
            var job = db.jobs.SingleOrDefault(j => j.JobId == id);

            return View(job);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var job = db.jobs.SingleOrDefault(j => j.JobId == id);

            if (job == null)
            {
                return Json("Job Not Found");
            }

            db.jobs.Remove(job);
            db.SaveChanges();

            return Json("Job Deleted Successfully");
           

           

        }
    }
}

JobOffers/Views/Job/Details.cshtml
@model JobOffers.Models.Job
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<lable>Job Title</lable> @Model.JobTitle
<br />
<lable>Job Content</lable> @Model.JobContent
<br />
@Html.ActionLink("Back To Index", "Index")

JobOffers/Views/Job/Index.cshtml
@model IEnumerable<JobOffers.Models.Job>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@Html.ActionLink("Add New", "New");
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td> Category</td>
            <td>Job Name </td>
            <td> Job Content</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </thead>

    <tbody>
        @foreach (var job in Model)
        {
            <tr>
                <td>@job.Category.CategoryName</td>
                <td>@job.JobTitle</td>
                <td>@job.JobContent</td>
                <td>@Html.ActionLink("Details","Details",new{id = job.JobId})</td>
                <td>@Html.ActionLink("Edit", "Edit", new {id = job.JobId })</td>
                <td><button class="btn btn-link jsdelete" job-id=@job.JobId >Delete</button> </td>
            </tr>
        }
    </tbody>

</table>


@section scripts{

   <script>
       $(document).ready(function () {

           $('.jsdelete').click(function () {

               var button = $(this);
               if (confirm("Are you sure you want delete this job")) {
                   $.ajax({
                       type: 'Post',
                       url: '@Url.Action("Delete","Job")',
                       data: {

                           id: button.attr('job-id')
                       },
                       success: function (data) {

                           button.parents('tr').remove().fadeOut("slow");
                       }

                   });

               }
             

           });
       });
    </script>
}

JobOffers/Views/Job/New.cshtml
@model JobOffers.ViewModel.JobViewModel
@{
    ViewBag.Title = "New";
}

<h2>New</h2>

@using (Html.BeginForm("Save","Job"))
{
    <div class="form-group">
        @Html.LabelFor(m=> m.job.JobTitle)
        @Html.TextBoxFor(m => m.job.JobTitle, new  {@class="form-control" })

    </div>
    
    <div class="form-group">
        @Html.LabelFor(m=> m.job.JobContent)
        @Html.TextBoxFor(m => m.job.JobContent, new {@class="form-control" })
    </div>
    
    <div class="form-group">
        @Html.DropDownListFor(m => m.job.CategoryId, new SelectList(Model.Categories, "CategoryId", "CategoryName"), "Add Job Category", new { @class = "form-control" })
    </div>
    
    <div class="form-group">
        @Html.HiddenFor(m=> m.job.JobId)
        <button class="btn btn-primary">Save</button>
    </div>
}